namespace Shared 

module SampleData =

  open Shared.Units
  open Shared.Domain
  open System

  let SampleDayPrices_All() : (DayPrice list) =
      [ { id = "1"
          PriceSheetDate = DateTimeOffset.Parse "2020-05-16 12:00:00 +10"
          Pool = VIC
          Buyer = GrainCorp
          Grade = Grade "BAR1"
          Grain = Barley
          Site = Site "Horsham"
          SaleType = Cash
          Price =
              [ { Season = Season "20/21"
                  Price = AUD(aud.lift (decimal (245))) }
                { Season = Season "21/22"
                  Price = AUD(aud.lift (decimal (230))) } ] }
        { id = "2"
          PriceSheetDate = DateTimeOffset.Parse "2020-05-15 12:00:00 +10"
          Pool = VIC
          Buyer = GrainCorp
          Grade = Grade "BAR1"
          Grain = Barley
          Site = Site "Horsham"
          SaleType = Cash
          Price =
              [ { Season = Season "20/21"
                  Price = AUD(aud.lift (decimal (249))) }
                { Season = Season "21/22"
                  Price = AUD(aud.lift (decimal (230))) } ] }
        { id = "3"
          PriceSheetDate = DateTimeOffset.Parse "2020-05-14 12:00:00 +10"
          Pool = VIC
          Buyer = GrainCorp
          Grade = Grade "BAR1"
          Grain = Barley
          Site = Site "Horsham"
          SaleType = Cash
          Price =
              [ { Season = Season "20/21"
                  Price = AUD(aud.lift (decimal (240))) }
                { Season = Season "21/22"
                  Price = AUD(aud.lift (decimal (230))) } ] }
        { id = "4"
          PriceSheetDate = DateTimeOffset.Parse "2020-05-13 12:00:00 +10"
          Pool = VIC
          Buyer = GrainCorp
          Grade = Grade "BAR1"
          Grain = Barley
          Site = Site "Horsham"
          SaleType = Cash
          Price =
              [ { Season = Season "20/21"
                  Price = AUD(aud.lift (decimal (244))) }
                { Season = Season "21/22"
                  Price = AUD(aud.lift (decimal (230))) } ] }
        { id = "5"
          PriceSheetDate = DateTimeOffset.Parse "2020-05-12 12:00:00 +10"
          Pool = VIC
          Buyer = GrainCorp
          Grade = Grade "BAR1"
          Grain = Barley
          Site = Site "Horsham"
          SaleType = Cash
          Price =
              [ { Season = Season "20/21"
                  Price = AUD(aud.lift (decimal (246))) }
                { Season = Season "21/22"
                  Price = AUD(aud.lift (decimal (230))) } ] }
        { id = "6"
          PriceSheetDate = DateTimeOffset.Parse "2020-05-11 12:00:00 +10"
          Pool = VIC
          Buyer = GrainCorp
          Grade = Grade "BAR1"
          Grain = Barley
          Site = Site "Horsham"
          SaleType = Cash
          Price =
              [ { Season = Season "20/21"
                  Price = AUD(aud.lift (decimal (248))) }
                { Season = Season "21/22"
                  Price = AUD(aud.lift (decimal (230))) } ] }
        { id = "7"
          PriceSheetDate = DateTimeOffset.Parse "2020-05-10 12:00:00 +10"
          Pool = VIC
          Buyer = GrainCorp
          Grade = Grade "BAR1"
          Grain = Barley
          Site = Site "Horsham"
          SaleType = Cash
          Price =
              [ { Season = Season "20/21"
                  Price = AUD(aud.lift (decimal (255))) }
                { Season = Season "21/22"
                  Price = AUD(aud.lift (decimal (230))) } ] }
        { id = "8"
          PriceSheetDate = DateTimeOffset.Parse "2020-05-19 12:00:00 +10"
          Pool = VIC
          Buyer = GrainCorp
          Grade = Grade "BAR1"
          Grain = Barley
          Site = Site "Horsham"
          SaleType = Cash
          Price =
              [ { Season = Season "20/21"
                  Price = AUD(aud.lift (decimal (260))) }
                { Season = Season "21/22"
                  Price = AUD(aud.lift (decimal (230))) } ] }
        { id = "11"
          PriceSheetDate = DateTimeOffset.Parse "2020-05-16 12:00:00 +10"
          Pool = VIC
          Buyer = GrainCorp
          Grade = Grade "BAR1"
          Grain = Barley
          Site = Site "Stawell"
          SaleType = Cash
          Price =
              [ { Season = Season "20/21"
                  Price = AUD(aud.lift (decimal (245))) }
                { Season = Season "21/22"
                  Price = AUD(aud.lift (decimal (230))) } ] }
        { id = "12"
          PriceSheetDate = DateTimeOffset.Parse "2020-05-15 12:00:00 +10"
          Pool = VIC
          Buyer = GrainCorp
          Grade = Grade "BAR1"
          Grain = Barley
          Site = Site "Stawell"
          SaleType = Cash
          Price =
              [ { Season = Season "20/21"
                  Price = AUD(aud.lift (decimal (249))) }
                { Season = Season "21/22"
                  Price = AUD(aud.lift (decimal (230))) } ] }
        { id = "13"
          PriceSheetDate = DateTimeOffset.Parse "2020-05-14 12:00:00 +10"
          Pool = VIC
          Buyer = GrainCorp
          Grade = Grade "BAR1"
          Grain = Barley
          Site = Site "Stawell"
          SaleType = Cash
          Price =
              [ { Season = Season "20/21"
                  Price = AUD(aud.lift (decimal (240))) }
                { Season = Season "21/22"
                  Price = AUD(aud.lift (decimal (230))) } ] }
        (*{ id = "14"
          PriceSheetDate = DateTimeOffset.Parse "2020-05-13 12:00:00 +10"
          Pool = VIC
          Buyer = GrainCorp
          Grade = Grade "BAR1"
          Grain = Barley
          Site = Site "Stawell"
          SaleType = Cash
          Price =
              [ { Season = Season "20/21"
                  Price = AUD(aud.lift (decimal (244))) }
                { Season = Season "21/22"
                  Price = AUD(aud.lift (decimal (230))) } ] }*)
        { id = "15"
          PriceSheetDate = DateTimeOffset.Parse "2020-05-12 12:00:00 +10"
          Pool = VIC
          Buyer = GrainCorp
          Grade = Grade "BAR1"
          Grain = Barley
          Site = Site "Stawell"
          SaleType = Cash
          Price =
              [ { Season = Season "20/21"
                  Price = AUD(aud.lift (decimal (246))) }
                { Season = Season "21/22"
                  Price = AUD(aud.lift (decimal (230))) } ] }
        { id = "16"
          PriceSheetDate = DateTimeOffset.Parse "2020-05-11 12:00:00 +10"
          Pool = VIC
          Buyer = GrainCorp
          Grade = Grade "BAR1"
          Grain = Barley
          Site = Site "Stawell"
          SaleType = Cash
          Price =
              [ { Season = Season "20/21"
                  Price = AUD(aud.lift (decimal (248))) }
                { Season = Season "21/22"
                  Price = AUD(aud.lift (decimal (230))) } ] }
        { id = "17"
          PriceSheetDate = DateTimeOffset.Parse "2020-05-10 12:00:00 +10"
          Pool = VIC
          Buyer = GrainCorp
          Grade = Grade "BAR1"
          Grain = Barley
          Site = Site "Stawell"
          SaleType = Cash
          Price =
              [ { Season = Season "20/21"
                  Price = AUD(aud.lift (decimal (255))) }
                { Season = Season "21/22"
                  Price = AUD(aud.lift (decimal (230))) } ] }
        { id = "18"
          PriceSheetDate = DateTimeOffset.Parse "2020-05-19 12:00:00 +10"
          Pool = VIC
          Buyer = GrainCorp
          Grade = Grade "BAR1"
          Grain = Barley
          Site = Site "Stawell"
          SaleType = Cash
          Price =
              [ { Season = Season "20/21"
                  Price = AUD(aud.lift (decimal (260))) }
                { Season = Season "21/22"
                  Price = AUD(aud.lift (decimal (230))) } ] } 
        { id = "19"
          PriceSheetDate = DateTimeOffset.Parse "2020-05-16 12:00:00 +10"
          Pool = VIC
          Buyer = GrainCorp
          Grade = Grade "BAR1"
          Grain = Barley
          Site = Site "Ballarat"
          SaleType = Cash
          Price =
              [ { Season = Season "20/21"
                  Price = AUD(aud.lift (decimal (255))) }
                { Season = Season "21/22"
                  Price = AUD(aud.lift (decimal (290))) } ] }
        { id = "20"
          PriceSheetDate = DateTimeOffset.Parse "2020-05-15 12:00:00 +10"
          Pool = VIC
          Buyer = GrainCorp
          Grade = Grade "BAR1"
          Grain = Barley
          Site = Site "Ballarat"
          SaleType = Cash
          Price =
              [ { Season = Season "20/21"
                  Price = AUD(aud.lift (decimal (200))) }
                { Season = Season "21/22"
                  Price = AUD(aud.lift (decimal (210))) } ] }
        { id = "21"
          PriceSheetDate = DateTimeOffset.Parse "2020-05-14 12:00:00 +10"
          Pool = VIC
          Buyer = GrainCorp
          Grade = Grade "BAR1"
          Grain = Barley
          Site = Site "Ballarat"
          SaleType = Cash
          Price =
              [ { Season = Season "20/21"
                  Price = AUD(aud.lift (decimal (299))) }
                { Season = Season "21/22"
                  Price = AUD(aud.lift (decimal (289))) } ] }
                  ]
